- name: "run docker container"
  ansible.builtin.import_role:
    name: common
    tasks_from: run_docker_container.yml
  vars:
    image_name: mongo-express
    exposed_port: 8081
    published_port: 8083:8081  