- name: Install Docker
  ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

- name: "gcloud docker authentication"
  ansible.builtin.shell: yes | gcloud auth configure-docker europe-central2-docker.pkg.dev

- name: Pull docker image from Artifact registry
  docker_container: 
    image: europe-central2-docker.pkg.dev/terraform-ansible-389111/docker-images/server-app:1.0.0
    pull: yes
    name: server-app
    env:
      DB_HOST: "192.168.1.2"
      DB_PORT: "27017"
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    state: started
    restart_policy: always